apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-event-listener
spec:
  serviceAccountName: build-bot
  triggers:
  - name: build-trigger
    template:
      ref: build-trigger-template
    bindings:
    - ref: build-trigger-binding
