apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ops-dev-event-listener
spec:
  serviceAccountName: build-bot
  triggers:
  - name: ops-dev-trigger
    template:
      ref: ops-dev-trigger-template
    bindings:
    - ref: ops-dev-trigger-binding
